version: "3"
services:
  postgres:
    build: ./database
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432
  go-api:
    build: ./src/main/backend
    ports:
      - 8081:8081
    depends_on:
      - postgres
    links:
      - postgres
  react-app:
    build: ./src/main/frontend
    ports:
      - 3000:3000